### ISSUE TITLE
CarAI handled to asset editor -> serialized in assets.

### ISSUE THREAD

**Issue by V10lator** [sschoener/cities-skylines-no-despawn#2]
Currently the Asset Alfa Romeo 164 ( http://steamcommunity.com/sharedfiles/filedetails/?id=453021816 ) has this problem: The Car AI from your mod got serialized as the author of the asset used it, now others can't load it:

System.IO.InvalidDataException: Loading custom asset failed:['alfar164' [CustomAssetMetaData, 54c3f94290aee8b7f201b368b7f54aa0, in package ''453021816' [ /home/v10lator/.ssd/SteamApps/steamapps/workshop/content/255710/453021816/alfar164.crp]' (1111740, 2048)]]
Unknown type to deserialize CitiesSkylinesNoDespawnMod.VehicleAIMod.PassengerCarAIMod, CitiesSkylinesNoDespawnMod, Version=1.0.5577.29262, Culture=neutral, PublicKeyToken=null [Modding]

**Comment by sschoener** [comment]
Thank you for bringing this to my attention. For all I know, all mods swapping out the AI classes should face similar issues. I will investigate what the best way to fix this problem is.

**Comment by V10lator** [comment]
You're right, many mods face this problem. For now I'm coding a mod which allows to reset the AI to its base ( http://images.akamai.steamusercontent.com/ugc/539650744910818498/F2F3AF744A3360837ABE22B9F1C4D1933F99AB27/ ) but ofc. this will just be a workaround for asset creators till all mods are fixed. :)

**Comment by sschoener** [comment]
I have had a look around and it seems like Traffic++ also encountered that bug. They simply reset the AI classes when the game is unloaded. I will most likely go for that as well (simple and effective).

**Comment by sschoener** [comment]
Fixed.
